spring:
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl:
          auto: none
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false

